package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            feature {
                type = "sonar-qube"
                id = "PROJECT_EXT_11"
                param("useToken", "true")
                param("name", "TeamCity Sonar")
                param("id", "41b1151a-9b47-4ad6-886e-3f44f456b81b")
                param("url", "https://sonar.elhub.cloud")
                param("token", "scrambled:c3FhXzUwNzg3YTA5NWQyNTY4YzA0NjdjNTMyOTcyMWNiMTRmNTM1YjZjYmI=")
            }
        }
    }
}
